project:
  type: website
  output-dir: docs

website:
  title: "Martin Pl√∂derl"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: publications/index.qmd
        text: Publications
      - href: CV/index.qmd
        text: CV
      - href: cycling/index.qmd
        text: Cycling
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

